import Head from "next/head";
import dynamic from "next/dynamic";

import Search from '../components/Search';
import styles from "../styles/Home.module.css";

export default function Home() {
  const MapWithNoSSR = dynamic(() => import("../components/Map"), {
    ssr: false,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Country Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id="map" className={styles.map}>
          <MapWithNoSSR />
        </div>
        <Search />
      </main>
    </div>
  );
}
