import Head from "next/head";
import dynamic from "next/dynamic";

import Search from "../components/Search";
import Info from "../components/Info";
import Store, {StoreContext} from "../store";
import { useContext } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const MapWithNoSSR = dynamic(() => import("../components/Map"), {
    ssr: false,
  });

  const [state, dispatch]: any = useContext(StoreContext);

  const validLatLngCountries =
    (state?.searchDetails?.length &&
      state.searchDetails.filter((item) => item.latlng[0] && item.latlng[1])) ||
    [];

  console.log("state: ", state, validLatLngCountries);

  const center: Array<number> = validLatLngCountries.length
    ? [validLatLngCountries[0].latlng[1], validLatLngCountries[0].latlng[0]]
    : [-0.481, 51.323];

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Country Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <main className={styles.main}>
          <div id="map" className={styles.map}>
            <MapWithNoSSR data={validLatLngCountries} center={center}/>
          </div>
          <Search />
          <Info />
        </main>
      
    </div>
  );
}
